# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('identity', models.CharField(max_length=20, verbose_name='\u8eab\u4efd')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u767b\u9646\u4fe1\u606f',
            },
        ),
    ]
